<div class="container">
    <h2>Sign up using this form</h2>

    <p><?php echo $this->flashSession->output() ?></p>

    <?php echo $this->tag->form("user/add"); ?>

        <div class="form-group">
            <label for="fame">First Name</label>
            <?php echo $form->render('fname'); ?>
        </div>
	<div class="form-group">
            <label for="lname">Last Name</label>
            <?php echo $form->render('lname'); ?>
        </div>

        <div class="form-group">
            <label for="email">E-Mail</label>
            <?php echo $form->render('email'); ?>
        </div>
		<?php if($form->showPassowrd){ ?>
        <div class="form-group">
            <label for="password">Password</label>
            <?php echo $form->render('password'); ?>
        </div>

        <div class="form-group">
            <label for="confirm_password">Confirm Password</label>
            <?php echo $form->render('confirm_password'); ?>
        </div>
		<?php } else { echo $form->render('id'); }?>
    
    <div class="form-group">
            <label for="gender">Gender</label>
            <?php echo $form->render('gender'); ?>
        </div>

        <div class="form-group">
            <?php echo $form->render('submit'); ?>
        </div>

    </form>
    <a href="http://localhost/assignment/user/view">View Users</a>
</div>